// <auto-generated />
namespace StudentCourseManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class finalmg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finalmg));
        
        string IMigrationMetadata.Id
        {
            get { return "202403230402178_finalmg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
